# fos-data-engineering

to install dependencies, run: `pip install -r requirements.txt`

erreur dans le crone :
J'ai crié une image avec build puis j'ai fais docker run my app : le cron marche chaque 1 minute mais le problème qu'il m'affiche une erreur : python not found du coup il n'exécute pas etl .Py 
remarque : j'ai essayé avec FROM python:latest et FROM python:3.8 la même chose 
